### ISSUE TITLE
Add output of all posts of the current user

### ISSUE THREAD

**Issue by KurnakovMaksim** [KurnakovMaksim/NotSocialNetwork_Blazor#4]

**Comment by Ulyanov-programmer** [comment]
The creation of a PublicationController for this functionality is expected. #13

**Comment by Ulyanov-programmer** [comment]
Commit 39f8a5b6687ed4edfc8bfa0344d3e9762523b92c implemented this functionality in the user interface, previously it was implemented in the API.
